version: '3.2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION    
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      #ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    container_name: logstash    
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"  
    networks:
      - elk
    #command: logstash -f /config/product.logstash.conf  
    depends_on:
      - rabbitmq
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION    
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true  
    ports:
      - 5601:5601      
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

  rabbitmq:
    build:
      context: rabbitmq/
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION  
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - type: volume
        source: rabbitmq_elk
        target: /var/lib/rabbitmq      
    environment:
      RABBITMQ_ERLANG_COOKIE: stack_elk
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: elastic
      RABBITMQ_DEFAULT_VHOST: elastic      
    networks: 
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
    driver: local
  rabbitmq_elk:
    driver: local  
